//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiTiendaMejorada.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mi_TiendaEntities : DbContext
    {
        public Mi_TiendaEntities()
            : base("name=Mi_TiendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_productos> tb_productos { get; set; }
        public virtual DbSet<tb_proveedores> tb_proveedores { get; set; }
        public virtual DbSet<tb_ventas> tb_ventas { get; set; }
    }
}
