//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renta_de_Peliculas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Rentas
    {
        public int idRenta { get; set; }
        public int idCliente { get; set; }
        public int idPelicula { get; set; }
        [Required]
        [Column(TypeName = "date")]
        public System.DateTime fecha { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Peliculas Peliculas { get; set; }
        public virtual Rentas Rentas1 { get; set; }
        public virtual Rentas Rentas2 { get; set; }
    }
}
